### ISSUE TITLE
Styles for elements

### ISSUE THREAD

**Issue by SergeyMelnyk** [josemoyab/react-ui-form-builder#5]
Hi! i try use this module and have trouble with styles, my formbuilder look like have not any styles, may any body help me?

my dependencies: 
```
"dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-form-builder2": "^0.5.12",
    "react-scripts": "3.4.1",
    "react-ui-form-builder": "^0.0.18"
  },
```

 [
![Снимок экрана 2020-07-16 в 10 25 26](https://user-images.githubusercontent.com/39995312/87640047-ce418b80-c74e-11ea-8727-517cc4e73e93.png)
](url)

**Comment by josemoyab** [comment]
Hello @SergeyMelnyk, you should add semantic-ui-react to your dependencies

**Comment by josemoyab** [comment]
Closed due inactivity
